trigger:
- main  # Branche déclencheur (ajustez selon vos besoins)

pool:
  name: 'monpool'  # Remplacez par le nom de votre pool d'agents auto-hébergé
  demands: 
    - agent.name -equals DESKTOP-7VGJL6D  # Ajoutez cette ligne si vous voulez spécifier un agent précis

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'  # Spécifiez la version de Node.js utilisée
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'
